version: '3.8'

services:
  django:
    build: ./
    command: gunicorn practice.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    env_file: ./.env
    volumes:
      - .:/usr/src/app
      - static_volume:/usr/src/app/staticfiles

  nginx:
    image: nginx:stable-alpine
    ports:
      - 80:80
    volumes:
      - static_volume:/usr/src/app/staticfiles
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      -  django

volumes:
  static_volume: